Webworker code
DAT2G7/grid-server pull request #4
Opened 2023-03-31 12:34 UTC by TheMagzuz

### Purpose
Adds the code needed to start a core, and exposes the functions that the core needs to communicate with the project server, to the core

### Primary Changes
- Implement `getData`, `sendResult` and `onDone`
- Inject these functions on the global `self` object so that the core has access to them
- Add downloading and running the core in the webworker
- Add some rough error handling and logging on the client

### Notes
- There are currently no tests, due to the way that the webworker code works
- Loading the webworker code currently causes an error in the console, due to the fact that the TypeScript compiler is currently configured to build to CommonJS modules, which are not supported in the browser. The webworker code still runs fine though

2023-04-11 08:24 UTC, TheMagzuz commented
We need to clear indexdb when a core is done running, since they might use that to persist data

2023-04-17 13:23 UTC, 7H30D0R requested changes

2023-04-17 13:23 UTC, 7H30D0R commented on src/public/static/js/client/worker.ts
> +            `/api/client/core/${setupData.projectId}/job/${setupData.jobId}/task/${setupData.taskId}`
Still using `api/client/core/` instead of `api/client/project/`, this needs to be updated.

2023-04-17 13:23 UTC, 7H30D0R commented on src/public/static/js/client/worker.ts
> +            `/api/client/core/${setupData.projectId}/job/${setupData.jobId}/task/${setupData.taskId}`,
Still using `api/client/core/` instead of `api/client/project/`, this needs to be updated.

2023-04-17 13:23 UTC, 7H30D0R commented on src/public/static/js/client/client.ts
> +                // TODO: better communication with the user
Is this todo still relevant?

2023-04-20 12:36 UTC, 7H30D0R approved these changes
LGTM 👍

2023-04-21 07:23 UTC, merged